### ISSUE TITLE
Error when trying to use audiostretchy

### ISSUE THREAD

**Issue by bekaba** [twardoch/audiostretchy#3]
Hello, I m getting this error when trying to run audiostretchy 1.3.1.
I tried uninstalling and reinstalling it but it doesn't seem to help could you tell me how to fix this please?
I am getting this error when I run : audiostretchy m1.mp3 m12.mp3 -r1.25
Traceback (most recent call last):
"C:\Users\bekaba\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main return _run_code(code, main_globals, None, File "C:\Users\bekaba\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code exec(code, run_globals) File "C:\Users\bekaba\AppData\Local\Programs\Python\Python310\Scripts\audiostretchy.exe\__main__.py", line 7, in <module> File "C:\Users\bekaba\AppData\Local\Programs\Python\Python310\lib\site-packages\audiostretchy\__main__.py", line 10, in cli fire.Fire(stretch_audio) File "C:\Users\bekaba\AppData\Local\Programs\Python\Python310\lib\site-packages\fire\core.py", line 141, in Fire component_trace = _Fire(component, args, parsed_flag_args, context, name) File "C:\Users\bekaba\AppData\Local\Programs\Python\Python310\lib\site-packages\fire\core.py", line 475, in _Fire component, remaining_args = _CallAndUpdateTrace( File "C:\Users\bekaba\AppData\Local\Programs\Python\Python310\lib\site-packages\fire\core.py", line 691, in _CallAndUpdateTrace component = fn(*varargs, **kwargs) File "C:\Users\bekaba\AppData\Local\Programs\Python\Python310\lib\site-packages\audiostretchy\stretch.py", line 336, in stretch_audio audio_stretch.open(input_path) File "C:\Users\bekaba\AppData\Local\Programs\Python\Python310\lib\site-packages\audiostretchy\stretch.py", line 57, in open self.open_mp3(audio_file) File "C:\Users\bekaba\AppData\Local\Programs\Python\Python310\lib\site-packages\audiostretchy\stretch.py", line 72, in open_mp3 with open(BytesIO(), "wb") as wav_io: TypeError: expected str, bytes or os.PathLike object, not BytesIO

**Comment by twardoch** [comment]
Fixed. Run the upgrade: 

```
python3 -m pip install --upgrade audiostretchy[all]
```

**Comment by bekaba** [comment]
Thank you I seem to be getting this error now after upgrading:
audiostretchy m1.mp3 m12.mp3 -r1.25
Exception ignored in: <function Wave_write.__del__ at 0x000001C091805630>
Traceback (most recent call last):
  File "C:\Users\bekaba\AppData\Local\Programs\Python\Python310\lib\wave.py", line 326, in __del__
    self.close()
  File "C:\Users\bekaba\AppData\Local\Programs\Python\Python310\lib\wave.py", line 447, in close
    self._file.flush()
ValueError: I/O operation on closed file.
Traceback (most recent call last):
  File "C:\Users\bekaba\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\bekaba\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\bekaba\AppData\Local\Programs\Python\Python310\Scripts\audiostretchy.exe\__main__.py", line 7, in <module>
  File "C:\Users\bekaba\AppData\Local\Programs\Python\Python310\lib\site-packages\audiostretchy\__main__.py", line 10, in cli
    fire.Fire(stretch_audio)
  File "C:\Users\bekaba\AppData\Local\Programs\Python\Python310\lib\site-packages\fire\core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "C:\Users\bekaba\AppData\Local\Programs\Python\Python310\lib\site-packages\fire\core.py", line 475, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "C:\Users\bekaba\AppData\Local\Programs\Python\Python310\lib\site-packages\fire\core.py", line 691, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "C:\Users\bekaba\AppData\Local\Programs\Python\Python310\lib\site-packages\audiostretchy\stretch.py", line 368, in stretch_audio
    audio_stretch.save(output_path)
  File "C:\Users\bekaba\AppData\Local\Programs\Python\Python310\lib\site-packages\audiostretchy\stretch.py", line 132, in save
    self.save_mp3(audio_file)
  File "C:\Users\bekaba\AppData\Local\Programs\Python\Python310\lib\site-packages\audiostretchy\stretch.py", line 154, in save_mp3
    encoder.set_mod(
AttributeError: 'mp3.Encoder' object has no attribute 'set_mod'. Did you mean: 'set_mode'?

**Comment by twardoch** [comment]
Try again with:

python3 -m pip install --upgrade audiostretchy[all]

I had followed the code sample from https://pypi.org/project/pymp3/ for the Windows MP3 writer but it seems that the code example is wrong there. So now I made "set_mode" now instead of "set_mod". 

Let me know if that helped. 

I plan to rewrite audiostretchy to use a different back-end for MP3 reading and writing (https://github.com/spotify/pedalboard which will allow to do more cool things including running VST plugins), but that's not for now. :)

**Comment by bekaba** [comment]
I am still getting an error. Also, it seems that when used with wav files audio-stretchy works fine on my computer, the problem only appears when I try to use it with mp3 files.
Here is the error I m getting now:
audiostretchy m1.mp3 m12.mp3 --ratio 1.25
Exception ignored in: <function Wave_write.__del__ at 0x00000212CAC75630>
Traceback (most recent call last):
  File "C:\Users\bekaba\AppData\Local\Programs\Python\Python310\lib\wave.py", line 326, in __del__
    self.close()
  File "C:\Users\bekaba\AppData\Local\Programs\Python\Python310\lib\wave.py", line 447, in close
    self._file.flush()
ValueError: I/O operation on closed file.
Traceback (most recent call last):
  File "C:\Users\bekaba\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\bekaba\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\bekaba\AppData\Local\Programs\Python\Python310\Scripts\audiostretchy.exe\__main__.py", line 7, in <module>
  File "C:\Users\bekaba\AppData\Local\Programs\Python\Python310\lib\site-packages\audiostretchy\__main__.py", line 10, in cli
    fire.Fire(stretch_audio)
  File "C:\Users\bekaba\AppData\Local\Programs\Python\Python310\lib\site-packages\fire\core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "C:\Users\bekaba\AppData\Local\Programs\Python\Python310\lib\site-packages\fire\core.py", line 475, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "C:\Users\bekaba\AppData\Local\Programs\Python\Python310\lib\site-packages\fire\core.py", line 691, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "C:\Users\bekaba\AppData\Local\Programs\Python\Python310\lib\site-packages\audiostretchy\stretch.py", line 368, in stretch_audio
    audio_stretch.save(output_path)
  File "C:\Users\bekaba\AppData\Local\Programs\Python\Python310\lib\site-packages\audiostretchy\stretch.py", line 132, in save
    self.save_mp3(audio_file)
  File "C:\Users\bekaba\AppData\Local\Programs\Python\Python310\lib\site-packages\audiostretchy\stretch.py", line 155, in save_mp3
    mp3.MODE_STEREO if nchannels == 2 else mp3.MODE_SINGLE_CHANNEL
NameError: name 'nchannels' is not defined

**Comment by twardoch** [comment]
It seems that you should convert to WAV with another app and only stretch WAV-to-WAV. That should work.

Fixing MP3 will take a while.

**Comment by Jothapunkt** [comment]
Hello, for anyone having the same issue, it seems this particular issue is caused by a small typo in save_mp3, attempting to use 'nchannels' rather than 'self.nchannels'. [I opened a tiny PR to fix this here.](https://github.com/twardoch/audiostretchy/pull/8)
